### ISSUE TITLE
Precog and LosSa

### ISSUE THREAD

**Issue by Bambiiqt** [XyzKangUI/RougeUI#3]
Will you be bringing back Precognito and LosSa for Cata

**Comment by Notmelody** [comment]
Hey I'd also like to know what happened to Precognito, and also why you dipped out of the arena addicts discord?

**Comment by XyzKangUI** [comment]
> Hey I'd also like to know what happened to Precognito, and also why you dipped out of the arena addicts discord?

First of all I don't see why you would post here and create a new issue about it. This git issue tracker is for the addon RougeUI and nothing else. 

To answer your two questions. Cataclysm has made Precognito redundant because the incoming heal is a native feature and tracking absorbs is made more accessible. Someone will sooner or later make a WeakAura or similar that makes use of these methods to mimic Precognito. Personally I have no incentive playing Cataclysm because the expansion doesn't appeal to me and is way too buggy. The incoming heal api currently reports 12-100x the value it should be reporting. 

The reason why I am no longer in that discord is because the admins are snakes. Jammin first of all that used to add code to private server addons that would act as "spyware" on users. He also tries to control what is allowed on the discord while his contribution there is near non existent. Synergist is a liar and got exposed by Vendethiel, who is the server owner that is pretty much a vague figure. 

Their side of the story would probably be that the things I have shared related to WoW were not appreciated and that I have been warned to not share certain things. But in reality you have to play WoW the way some people intend you to play it instead of playing the way it could be played. A simple example was that you could create a macro to `/targetlasttarget [noexists] /cast [noexists] Kick` to kick a player out of stealth, shadowmeld or feign death. There were more complex stuff I have shared and then it was used against me as if it could be automated. Surely, it could have been with the help of a third party program and if you would further tweak the macro. Two factors that were by all sudden added to the equation. It is like you sell a gas pistol and get blamed that it could be converted to a real one. For what its worth, I am a "terrorist" as Vendethiel called me. Anyway, I have gotten 6 different macro exploits fixed and 2 are still pending. All non related to the ClearTarget() exploit. Without disclosing more information, my approach worked and in the process Ive seen people their true colors while contributing towards a game with less exploits to be abused.

As for any other addon than RougeUI. I will probably update CombatTimer and some others.

**Comment by Notmelody** [comment]
Firstly, I couldn't really figure out a way to ask about the matter, so I apologise to go through this channel.

I had a feeling this was the reason why, because over the years I could glance at the discord and see you being very helpful to the community. It's a real shame it ended this way and those peopel should be ashamed for the way they've treated you.

Thanks for all your time, It was nice to see someone like you contribute the way that you did.

All the best

**Comment by XyzKangUI** [comment]
> Firstly, I couldn't really figure out a way to ask about the matter, so I apologise to go through this channel.

Thank you. I wish you the best as well.
